### ISSUE TITLE
パーツのマスパラメータを合わせる

### ISSUE THREAD

**Issue by YoheiKakiuchi** [IRSL-tut/robot_assembler_config_IRSL#1]
これまで適当にしていたが、シミュレーションが現実と同じ動となるために、
それなりに適切な、重さ、重心、慣性行列 をパーツの設定に入れたい

numpy-stlでstlのマスパラを得られるようだ
https://pypi.org/project/numpy-stl/

以下、テストコード
```
import numpy as np
from stl import mesh

mh = mesh.Mesh.from_file('1_box.stl')

vol, cog, iner = mh.get_mass_properties()

>>> import numpy as np
from stl import mesh
>>> >>> 
>>> mh = mesh.Mesh.from_file('1_box.stl') ## edge-length = 1.0
>>> vol, cog, iner = mh.get_mass_properties()
>>> vol
1.0
>>> cog
array([0., 0., 0.])
>>> iner
array([[ 0.16666667, -0.        , -0.        ],
       [-0.        ,  0.16666667, -0.        ],
       [-0.        , -0.        ,  0.16666667]])

>>> mh = mesh.Mesh.from_file('2_box.stl') ## edge-length = 2.0
>>> vol, cog, iner = mh.get_mass_properties()
>>> vol
8.0
>>> cog
array([0., 0., 0.])
>>> iner
array([[ 5.33333333, -0.        , -0.        ],
       [-0.        ,  5.33333333, -0.        ],
       [-0.        , -0.        ,  5.33333333]])
```

inerが何を表しているかだけれども、
正方形の慣性 https://mathwords.net/itiyonatyohokei
I = 1/6 * M * L^2

L = 1.0 m の鉄だと、M=8000 kg
I = 8000 * 1/6

L = 2.0 m の鉄だと、M=64000 kg
I = 1/6 * 64000 * 4
  = 8000 * 32/6

であるから iner に 密度をかけると慣性行列になる気がする

**Comment by Hiroaki-Masuzawa** [comment]
numpy-stlの結果がかなりおかしい気がします．
cube1.stl -> 原点中心に1000mm×1000mm×1000mmの立方体
cube2.stl  -> cube1.stlをZ方向に500mmずらしたもの
cube3.stl  -> cube1.stlをX,Y,Z方向それぞれ500mmずらしたもの

>>> import numpy as np
>>> from stl import mesh
>>> mh1 = mesh.Mesh.from_file('cube1.stl')
>>> vol1, cog1, iner1 = mh1.get_mass_properties()
>>> mh2 = mesh.Mesh.from_file('cube2.stl')
>>> vol2, cog2, iner2 = mh2.get_mass_properties()
>>> mh3 = mesh.Mesh.from_file('cube3.stl')
>>> vol3, cog3, iner3 = mh3.get_mass_properties()
>>> cog1, iner1
(array([0., 0., 0.]), array([[ 1.66666671e+14, -0.00000000e+00, -0.00000000e+00],
       [-0.00000000e+00,  1.66666671e+14, -0.00000000e+00],
       [-0.00000000e+00, -0.00000000e+00,  1.66666671e+14]]))
>>> cog2, iner2
(array([  0.        ,   0.        , 500.00000887]), array([[ 1.66666669e+14, -0.00000000e+00, -0.00000000e+00],
       [-0.00000000e+00,  1.66666669e+14, -0.00000000e+00],
       [-0.00000000e+00, -0.00000000e+00,  1.66666671e+14]]))
>>> cog3, iner3
(array([500.00000887, 500.00000887, 500.00000887]), array([[1.66666667e+14, 2.06056116e+06, 2.06056116e+06],
       [2.06056116e+06, 1.66666667e+14, 2.06056119e+06],
       [2.06056116e+06, 2.06056119e+06, 1.66666667e+14]]))


fusion360だと単位系や密度を合わせる方法がわからないかったので，
材質を水にした時のデータを乗せておきます．

ボディ (1)
面積	6.000E+06 mm^2
密度	0.001 g / mm^3
質量	9.983E+05 g
体積	1.000E+09 mm^3
物理マテリアル	水
外観	水 - クリア

境界領域
	長さ 	 1000.00 mm
	幅 	 1000.00 mm
	高さ 	 1000.00 mm

原点の慣性モーメント   (g mm^2)
	Ixx = 1.664E+11
	Ixy = -4.760E-05
	Ixz = -4.760E-05
	Iyx = -4.760E-05
	Iyy = 1.664E+11
	Iyz = 0.00
	Izx = -4.760E-05
	Izy = 0.00
	Izz = 1.664E+11
重心	0.00 mm, 0.00 mm, 0.00 mm

重心の慣性モーメント   (g mm^2)
	Ixx = 1.664E+11
	Ixy = -4.760E-05
	Ixz = -4.760E-05
	Iyx = -4.760E-05
	Iyy = 1.664E+11
	Iyz = 0.00
	Izx = -4.760E-05
	Izy = 0.00
	Izz = 1.664E+11





ボディ (1)
面積	6.000E+06 mm^2
密度	0.001 g / mm^3
質量	9.983E+05 g
体積	1.000E+09 mm^3
物理マテリアル	水
外観	水 - クリア

境界領域
	長さ 	 1000.00 mm
	幅 	 1000.00 mm
	高さ 	 1000.00 mm

原点の慣性モーメント   (g mm^2)
	Ixx = 4.160E+11
	Ixy = -4.760E-05
	Ixz = 4.760E-05
	Iyx = -4.760E-05
	Iyy = 4.160E+11
	Iyz = 0.00
	Izx = 4.760E-05
	Izy = 0.00
	Izz = 1.664E+11
重心	0.00 mm, 0.00 mm, 500.00 mm

重心の慣性モーメント   (g mm^2)
	Ixx = 1.664E+11
	Ixy = -4.760E-05
	Ixz = 1.041E-05
	Iyx = -4.760E-05
	Iyy = 1.664E+11
	Iyz = 0.00
	Izx = 1.041E-05
	Izy = 0.00
	Izz = 1.664E+11




ボディ (1)
面積	6.000E+06 mm^2
密度	0.001 g / mm^3
質量	9.983E+05 g
体積	1.000E+09 mm^3
物理マテリアル	水
外観	水 - クリア

境界領域
	長さ 	 1000.00 mm
	幅 	 1000.00 mm
	高さ 	 1000.00 mm

原点の慣性モーメント   (g mm^2)
	Ixx = 6.655E+11
	Ixy = -2.496E+11
	Ixz = -2.496E+11
	Iyx = -2.496E+11
	Iyy = 6.655E+11
	Iyz = -2.496E+11
	Izx = -2.496E+11
	Izy = -2.496E+11
	Izz = 6.655E+11
重心	500.00 mm, 500.00 mm, 500.00 mm

重心の慣性モーメント   (g mm^2)
	Ixx = 1.664E+11
	Ixy = 0.00
	Ixz = 0.00
	Iyx = 0.00
	Iyy = 1.664E+11
	Iyz = 0.00
	Izx = 0.00
	Izy = 0.00
	Izz = 1.664E+11


[stls.zip](https://github.com/IRSL-tut/robot_assembler_config_IRSL/files/11351255/stls.zip)

**Comment by YoheiKakiuchi** [comment]
IRSLのprivateですが、inertia_matrixを評価するプログラムを上げています
https://github.com/IRSL-tut/irsl_common/blob/main/python/inertia_matrix.py


```numpy.dot(numpy.dot(rot.transpose(), iner), rot) =``` はrotationして対角行列にしたもので、対角成分以外は10^-16以下で誤差です。
経験上rotation-matrixが入ったりすると、誤差が 10^-15 出てしまうものです。

真値は 1.66666667e+14 なので、1.66666665e+14 または 1.66666671e+14 が出てきていますが、
誤差の割合は 10^-8くらいですね。
```
(- (/ 1.66666665e+14 1.66666667e+14) 1.0) => -1.199999999368373e-08
(- (/ 1.666666671e+14 1.66666667e+14) 1.0) => 6.000000496442226e-10
```

rotationは随分ありますが、そもそも正方形は慣性行列は球と同じで、回転は出ても問題ないと思います。

~~~
>>> im_stl = np.array([[1.66666667e+14, 2.06056116e+06, 2.06056116e+06], [2.06056116e+06, 1.66666667e+14, 2.06056119e+06], [2.06056116e+06, 2.06056119e+06, \
1.66666667e+14]])
im_stl = np.array([[1.66666667e+14, 2.06056116e+06, 2.06056116e+06], [2.06056116e+06, 1.66666667e+14, 2.06056119e+06], [2.06056116e+06, 2.06056119e+06, 1.66\
666667e+14]])
>>> inertia_matrix_info(im_stl)
inertia_matrix_info(im_stl)
Inertia principal axis: [1.66666665e+14 1.66666671e+14 1.66666665e+14]
 rotation:
[[ 0.81649658  0.57735027 -0.        ]
 [-0.40824829  0.57735027 -0.70710678]
 [-0.40824829  0.57735027  0.70710678]]
numpy.dot(numpy.dot(rot.transpose(), iner), rot) =
 [[ 1.66666665e+14  1.62396894e-02  1.77485794e-03]
 [ 1.21238300e-02  1.66666671e+14 -1.56327331e-03]
 [-4.22459739e-03  5.83989529e-03  1.66666665e+14]]
Rotation: axis: [ 0.76927374  0.24450384 -0.5902845 ] angle: 0.9878610561599137 [radian]
~~~

ちなみに、fusionの計算だと、誤差ほぼありません。

~~~
>>> im_fusion = np.array([[1.664E+11, -4.760E-05, -4.760E-05],  [-4.760E-05, 1.664E+11, 0.00],  [-4.760E-05, 0.0, 1.664E+11]])
im_fusion = np.array([[1.664E+11, -4.760E-05, -4.760E-05],  [-4.760E-05, 1.664E+11, 0.00],  [-4.760E-05, 0.0, 1.664E+11]])
>>> inertia_matrix_info(im_fusion)
inertia_matrix_info(im_fusion)
Inertia principal axis: [1.664e+11 1.664e+11 1.664e+11]
 rotation:
[[ 9.14247716e-01  4.05155667e-01  2.77555756e-17]
 [-2.86488319e-01  6.46470759e-01 -7.07106781e-01]
 [-2.86488319e-01  6.46470759e-01  7.07106781e-01]]
numpy.dot(numpy.dot(rot.transpose(), iner), rot) =
 [[ 1.66400000e+11 -6.40929366e-05  3.30316425e-07]
 [-4.56827042e-05  1.66400000e+11 -5.52115980e-06]
 [-3.74392502e-06  9.30198954e-06  1.66400000e+11]]
Rotation: axis: [ 0.87507717  0.18521243 -0.44714237] angle: 0.8841945728168962 [radian]
~~~

真面目に計算してないですが、stlはデータがfloat(32bit)なのでstlとして点を移動させると誤差がのりやすいかもしれません。

いずれにしても、numpy-stlのinertiaは重心回りの慣性であって、問題があるほどの誤差ではないように見えます。


hingeで同じように算出、誤差があまりなければ使いやすそうな方を使うのでOKだと思います。

**Comment by YoheiKakiuchi** [comment]
マスパラメータの計算方法について、このIssueに書くか、READMEに書いてください。

確認方法としては、gazeboだと等価直方体を書いてくれるので重宝します。

```
roslaunch gazebo_ros empty_world.launch

rosrun gazebo_ros spawn_model -urdf -file /tmp/AssembleRobot.urdf -model robot
```

![gazebo_inertia](https://user-images.githubusercontent.com/2408164/237045806-ac98efda-b985-4867-a610-df17c6d73bac.png)

マージしてしまいましたが、
https://github.com/IRSL-tut/robot_assembler_config_IRSL/pull/3
において、z方向のマイナスが抜けてしまっているのではないかということが分かります。
慣性行列は重心回りで正しそうに見えます。

**Comment by Hiroaki-Masuzawa** [comment]
> マスパラメータの計算方法について、このIssueに書くか、READMEに書いてください。

ReadMeに追記するようにしました．(#4)


これまでに作ったパーツでnumpy-stlとFusionの慣性テンソルの計算結果を比較するとまずまずあっているようです．
ざっくり見ただけですが，1g/mm^2以上の値を持つ箇所については有効数字3桁ぐらいは一致しているようです．
